version: '3.3'

services:
    php:
        build:
            context: './docker/php/'
            args:
                PHP_VERSION: ${PHP_VERSION}
        depends_on:
            - redis
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
        networks:
            - backend
        volumes:
            - ./docker/php/conf.d/php.ini:/usr/local/etc/php/php.ini:ro
            - ${PROJECT_ROOT}/:/var/www/html/:cached
        working_dir: /var/www/html
        container_name: presentation-php

    apache:
        build:
            context: './docker/apache/'
            args:
                APACHE_VERSION: ${APACHE_VERSION}
        depends_on:
            - php
            - mysql
        networks:
            - frontend
            - backend
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ${PROJECT_ROOT}/:/var/www/html/
        stdin_open: true
        tty: true
        container_name: presentation-apache

    mysql:
        image: mysql:${MYSQL_VERSION}
        restart: always
        command: ['mysqld',
                  '--character-set-server=utf8mb4',
                  '--collation-server=utf8mb4_unicode_ci',
                  '--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - db-data:/var/lib/mysql
            - ./docker/mysql/dump:/docker-entrypoint-initdb.d
        networks:
            - backend
        ports:
            - 3306:3306
        container_name: presentation-mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        networks:
            - backend
        links:
            - mysql
        ports:
            - 8000:80
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        container_name: presentation-phpmyadmin

    redis:
        image: redis:4-alpine
        networks:
            - backend
        expose:
            - 6379
        container_name: presentation-redis

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    db-data:
